nthumodifications/courseweb

- package-lock.json
- package.json
- src/app/layout.tsx
- src/components/SideNav.tsx
- swapped icon lib for feather icons
- flexbox and icon size fix
> nav update

- src/app/[lang]/settings/page.tsx
- src/hooks/contexts/settings.tsx
> Theme cookies are now set to the origin path, fixing i18n

- src/app/[lang]/layout.tsx
- src/app/[lang]/timetable/calendar.ics/route.tsx
- src/app/[lang]/timetable/image/route.tsx
- src/app/[lang]/timetable/page.tsx
- src/app/[lang]/timetable/view/page.tsx
- src/app/[lang]/venues/[locationId]/page.tsx
- src/components/Courses/SelectCourseButton.tsx
- src/components/Header.tsx
- src/components/Timetable/CourseSearchbar.tsx
- src/components/Timetable/SemesterSwitcher.tsx
- src/components/Timetable/ShareRecievedDialog.tsx
- src/components/Timetable/TimetableCourseList.tsx
- src/const/semester.ts
- src/helpers/courses.ts
- src/helpers/roc.ts
- src/hooks/contexts/settings.tsx
- src/hooks/useUserTimetable.tsx
- src/types/courses.ts
> feat(semester): impl. multi semester handling

- src/app/[lang]/timetable/page.tsx
- src/components/Timetable/BlankTimeslotBody.tsx
- src/components/Timetable/TimeslotHeader.tsx
- src/components/Timetable/Timetable.tsx
- src/components/Timetable/TimetableSlot.tsx
- src/components/Timetable/TimetableSlotVertical.tsx
- src/components/Timetable/VenueChip.tsx
> ui: timetable improved UI

- src/app/[lang]/bus/stop/[stopId]/page.tsx
- src/app/[lang]/timetable/view/page.tsx
- src/components/Courses/RefineControls.tsx
- src/hooks/useUserTimetable.tsx
feat: useSWR add keepPreviousData: true for faster load
> feat: useSWR add keepPreviousData: true for faster load

- src/app/[lang]/courses/[courseId]/page.tsx
chore: sort related course by id
> ui: clamp related course width

- src/components/Timetable/TimetableSlotHorizontal.tsx
- src/components/Timetable/TimetableSlotVertical.tsx
fixes Timetable screenshot has weird shadows.
fixes #160
> fix: remove shadows on slots

- src/app/[lang]/apps/page.tsx
- src/app/[lang]/settings/page.tsx
- src/components/CCXPDownAlert.tsx
- src/components/Help/Tools.tsx
- src/hooks/contexts/settings.tsx
chore: temp disable ccxp
fix #168
> temp fix issue: headless ais, Error: Input bit Array is empty #168

- package-lock.json
- package.json
- src/app/[lang]/(mods-pages)/bus/bus/[busId]/page.tsx
- src/app/[lang]/(mods-pages)/bus/stop/[stopId]/page.tsx
- src/app/[lang]/(mods-pages)/student/grades/page.tsx
- src/app/[lang]/(mods-pages)/student/page.tsx
- src/app/[lang]/(mods-pages)/timetable/view/page.tsx
- src/app/[lang]/(mods-pages)/today/page.tsx
- src/app/[lang]/layout.tsx
- src/app/api/dashboard/alert/route.ts
- src/app/api/dashboard/weather/route.ts
- src/components/Courses/RefineControls.tsx
- src/components/ReactQuery.tsx
- src/components/Today/TodaySchedule.tsx
- src/hooks/contexts/useUserTimetable.tsx
- switched useSWR with useQuery
- queries are now offlineFirst
> BREAKING: Migrated from useSWR to React Query

- src/app/[lang]/(mods-pages)/(venues)/venues/@content/[locationId]/VenueTimetable.tsx
- src/app/[lang]/(mods-pages)/(venues)/venues/@content/[locationId]/page.tsx
This pull request adds lazy loading functionality to the VenueTimetableDynamic component in the venue page. It also fixes an issue where the Venue Timetable did not respect the client theme.
> Lazy load VenueTimetableDynamic component in venue page

- src/app/[lang]/(mods-pages)/bus/page.tsx
- src/app/[lang]/(mods-pages)/courses/CourseSearchContainer.tsx
- src/components/Help/Help.tsx
- src/components/Timetable/GroupByDepartmentButton.tsx
- src/components/Timetable/TimetableCourseList.tsx
- src/components/Timetable/TimetableSidebar.tsx
- src/components/Today/NoClassPickedReminder.tsx
- src/components/Today/TodaySchedule.tsx
- src/dictionaries/en.json
- src/dictionaries/zh.json
This PR adds English translations for for common places
> chore: add en translation

- src/app/[lang]/(mods-pages)/apps/AppItem.tsx
- src/app/[lang]/(mods-pages)/apps/page.tsx
- src/components/Today/TodaySchedule.tsx
- src/const/apps.ts
- src/dictionaries/en.json
- src/dictionaries/zh.json
This PR redesigns the apps page with categories, better namings, desktop UI, and more links
> feat: Redesigned Apps Page with Categories

- src/components/Timetable/TimetableCourseList.tsx
Reverts nthumodifications/courseweb#457
> Revert "fix: dragging course list in timetable for mobile"

- src/components/Timetable/TimetableCourseList.tsx
Reverts nthumodifications/courseweb#473
> Revert "Revert "fix: dragging course list in timetable for mobile""

- src/components/CourseDetails/CourseDetailsContainer.tsx
- src/components/CourseDetails/DateContributeForm.tsx
- src/components/Timetable/TimetableItemDrawer.tsx
- src/dictionaries/en.json
- src/dictionaries/zh.json
- src/lib/contrib_dates.ts
This PR adds Date Contribution to courses, as well as adds a dialog or timetable items on desktop
> feat: added DateContribution

- .github/dependabot.yml
This PR aims to improve dependaot grouping such that special cases are avoided.
> fix(deps): remove @capacitor and react-pdf-viewer from dependabot group

- src/app/[lang]/(mods-pages)/student/grades/GradesViewer.tsx
- src/dictionaries/en.json
- src/dictionaries/zh.json
Course names are now displayed based on the user's language settings.
> Added language support for course names in GradesViewer

- src/components/Timetable/TimetableItemDrawer.tsx
Will copying from the course list work just fine?
> Added delete button on course pop-up

- src/app/[lang]/(mods-pages)/(side-pages)/proxy-login/page.tsx
- src/app/[lang]/(mods-pages)/(side-pages)/web-for-beginners/auth/page.tsx
- src/app/[lang]/(mods-pages)/(side-pages)/web-for-beginners/comments-dates/page.tsx
- src/app/[lang]/(mods-pages)/(side-pages)/web-for-beginners/course/page.tsx
- src/app/[lang]/(mods-pages)/(side-pages)/web-for-beginners/grades/page.tsx
- src/app/[lang]/(mods-pages)/(side-pages)/web-for-beginners/misc/page.tsx
Introduce a detailed explanation of the NTHUMods Proxy Login process, including security measures and user information handling, with support for English and Chinese languages.
> Add explainer for NTHUMods Proxy Login

- src/app/[lang]/(mods-pages)/student/planner/layout.tsx
- src/app/[lang]/(mods-pages)/student/planner/planner-replication.tsx
- src/hooks/contexts/useAuth.tsx
This pull request includes updates to submodule commits, enhancements to the student planner layout, and added scope for authentication. The most important changes include updating submodule references, enhancing the student planner layout with a new provider, and expanding the scope for OpenID Connect authentication.
Enhancements to student planner layout:
* `src/app/[lang]/(mods-pages)/student/planner/layout.tsx`: Added `PlannerReplicationProvider` to the student planner layout to enhance functionality. ([src/app/[lang]/(mods-pages)/student/planner/layout.tsxR4](diffhunk://#diff-18666b04095c579b963113589590960fb0bb0a9cad21686b382c3cecb29cce52R4), [src/app/[lang]/(mods-pages)/student/planner/layout.tsxL14-R19](diffhunk://#diff-18666b04095c579b963113589590960fb0bb0a9cad21686b382c3cecb29cce …
> feat: add PlannerReplicationProvider for data synchronization
